List menu_items = [
  "Home",
  "My List",
  "Available for Download",
  "The Summer Edition",
  "Celebrating Disability with Dimension",
  "Hindi",
  "Tamil",
  "Punjabi",
  "Telugu",
  "Malayalam",
  "Marathi",
  "Bengali",
  "English",
  "Action",
  "Anime",
  "Award Winners",
  "Biographical",
  "Blockbusters",
  "Bollywood",
  "Kids & Family",
  "Comedies",
  "Documentaries",
  "Dramas",
  "Fantasy",
  "Hollywood",
  "Horror",
  "International",
  "Indian",
  "Music & Musicals",
  "Reality & Talk",
  "Romance",
  "Sci-Fi",
  "Stand-Up",
  "Thrillers",
  "United States",
  "Audio Description in English"
];
