name: netflix_part1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets\NetFlixLogo\NSymbol.jpg
    - assets\NetFlixLogo\NetFlixSymbol.jpg
    - assets\UserIcons\spiderman-figure-wallpaper_1198708-12521.avif
    - assets\UserIcons\picture-boy-with-red-background_969863-279244.avif
    - assets\UserIcons\drawing-anime-character-with-hoodie-it_1308172-177478.avif
    - assets\UserIcons\cartoon-man-with-blue-jacket-blue-jacket_983286-5842.avif
    - assets\UserIcons\boy-with-hoodie-that-says-hes-boy_1002151-24837.avif
    - assets\UserIcons\Netflix-avatar.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets\Fonts\static\Montserrat-Medium.ttf