name: leaderboard_page
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  badges: ^3.1.2
  pie_chart: ^5.4.0
  fl_chart: ^0.70.0
  floating_bottom_bar: ^0.0.3
  syncfusion_flutter_gauges: ^28.1.37
  syncfusion_flutter_charts: ^28.1.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
